### ISSUE TITLE
Allow message throttle settings

### ISSUE THREAD

**Issue by jimlambie** [dadiplus/queue-wrapper#1]
In the same way as deferring messages is possible, allow messages to be throttled, that is, run x times per specified duration.

**Comment by adamkdean** [comment]
👍

**Comment by jimlambie** [comment]
@adamkdean I think this should be done in the Queue module, rather than the wrapper. See the [queue throttle idea here](https://www.npmjs.com/package/job-broker)

**Comment by adamkdean** [comment]
Closed in favour of https://github.com/dadi/queue/issues/3
